# database.yml

development:
  adapter: postgresql
  database: didask-slack-db-development

test:
  adapter: postgresql
  database: didask-slack-db-test

production:
  adapter: postgresql
  database: didask-slack-db-production
